name: clean-command
on:
  repository_dispatch:
    types: [clean-command]
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Clean up pull requests and branches
      - name: Close Pull Requests
        uses: ./.github/close-pull-requests

      - name: Close Pull Requests
        uses: ./.github/close-pull-requests
        with:
          token: ${{ secrets.TEST_CASE_PAT }}
          repository: peter-evans/create-pull-request-tests-remote

      - name: Close Pull Requests
        uses: ./.github/close-pull-requests
        with:
          token: ${{ secrets.TEST_CASE_PAT }}
          repository: peter-evans/create-pull-request-tests-remote-private

      # Delete the test branch created in the fork
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CPR_MACHINE_USER_TOKEN }}
          repository: create-pull-request-machine-user/create-pull-request-tests
          ref: master
          path: create-pull-request-machine-user-fork
      - name: Delete fork branches
        working-directory: create-pull-request-machine-user-fork
        run: |
          git fetch
          git push --force --delete origin refs/heads/tests/push-branch-to-fork || true

      # Add reaction to the comment
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
