name: Misc tests
on: workflow_dispatch

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: commit-test

      - run: date +%s > test.txt

      - run: |
          # git config --global user.name 'Test Case'
          # git config --global user.email 'test-case@users.noreply.github.com'
          git -c author.name="Test Case" -c author.email="test-case@users.noreply.github.com" add test.txt
          git -c author.name="Test Case" -c author.email="test-case@users.noreply.github.com" commit -m "Test committer"
          git push
